config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'users/new'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email.downcase! }

  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, length: { maximum: 254 },
                    format: { with: /.+@.+\..+/i}, uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password, length: {minimum: 6, maximum: 21}, presence: true

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost? BCrypt::Engine::MIN_COST::BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute remember_digest, User.digest(remember_token)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute remember_digest, nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email:params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember_user
      redirect_to user
    end
  else
    flash.now[:danger] = 'Invalid email/password'
    #render 'new'
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = 'Your profile was successfully created!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "RoR Sample Web Application"
    if page_title.empty?
      base_title
    else
      page_title + '|' + base_title
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by id: session[:user_id]
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by id: user_id
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for user, options = {size: 50}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: 'gravatar'
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org">Ruby On Rails Tutorial</a> by <a href="http://www.michaelhartl.com">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%=	 link_to "About", about_path %></li>
      <li><%=	 link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org">News</a> </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed top navbar-inverse">
  <div class="container">
    <br>
    <%= link_to 'Sample App', root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
            <li><%= link_to 'Users', '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', '#' %></li>
                <li class="divider"></li>
                <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%=	 render 'layouts/shim' %>
  </head>
  <body>
  <%=	 render 'layouts/header' %>
    <div class="container">
      <%	 flash.each do |msg_type, msg| %>
          <%=	 content_tag :div, msg, class: "alert alert-#{msg_type}" %>
      <% end %>

      <%= yield %>
      <%=	 render 'layouts/footer' %>
      <%=	 debug params if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<%	 if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%	 pluralize @user.errors.count, 'error' %>
  </div>
  <ul>
    <%	 @user.errors.full_messages.each do |emsg| %>
    <li><%= emsg %></li>
        <% end %>
  </ul>
</div>
<%	 end %>

app/views/static_pages/about.html.erb
<title>About Page</title>
<h1>About Page</h1>
<p>The most attract french cuisine videos <a href="https://www.buzzfeed.com/marietelling/44-classic-french-meals-you-need-to-try-before-you-die?utm_term=.xk1mJBzQ00#.dwnx9GB4ee">here</a>
  <a href="https://screencasts.railstutorial.org"><br>RoR screencast series here</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1t>Contact</h1t>
<p>
  Contact me with LinkedIn.<br>
  <a href="linkedin.com/daniel-kliuchnikov">LinkedIn Profile</a>
</p>

app/views/static_pages/help.html.erb
<%provide(:title, "Help") %>
<title><%=yield (:title)%> Page</title>
<h1>Help Page</h1>
<p>
  There are no help here, buddy.
  <a href="http://www.railstutorial.org">But maybe, some help here.</a>
</p>

app/views/static_pages/home.html.erb
<div class="center jumborton">
  <h1>Welcome to sample web application</h1>
  <h2>This is home page for the <a href="http://www.railstutorial.org/">RoR Tutorial.</a></h2>

  <%= link_to "Sign Up, Now", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="center">
  <br>
  <%=	 link_to image_tag("tommy.jpg", alt: "Tommy logo", :class => "img-circle"),'' %>
</div>

app/views/users/new.html.erb
<%=	provide(:title, 'User Signup') %>
<h1>Sign Up</h1>
<div class="col-md-7 col-md-offset-3" style="text-align: center">
  <%=	simple_form_for @user, html: {class: 'form-vertical'} do |t| %>
      <%=	 render 'shared/error_messages' %>
      <%=	 t.input :name, class: 'form-control' %>
      <%=	 t.input :email ,class: 'form-control'%>
      <%=	 t.input :password, class: 'form-control'%>
      <%=	 t.input :password_confirmation, class: 'form-control' %>
      <%=	 t.submit "Create Account", class: "btn btn-primary" %>
      <% end %>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user-info">
      <h3>
        <%=	 gravatar_for @user %>
        <%=	@user.name  %>, <%=	 @user.email %>
      </h3>
    </section>
  </aside>
</div>